[package]
name = "network_sweep"
version = "0.1.0"
edition = "2021"


[dependencies]
ssdp-client = "*"
tokio = { version = "1", features = ["full"] }
futures = "0.3.4"
colour = "0.6.0"
prettytable-rs = "^0.8"
chrono = "0.4"